carts/urls.py
from django.urls import path
from .import views
urlpatterns =[
    path('carts/',views.carts,name='carts'),
    path('add_cart/<int:product_id>/',views.add_cart,name='add_cart'),
    path('remove_cart/<int:product_id>/<int:cart_item_id>/',views.remove_cart,name='remove_cart'),
    path('remove_cart_item/<int:product_id>/<int:cart_item_id>/',views.remove_cart_item,name='remove_cart_item'),
    path('checkout/',views.checkout,name='checkout')
]

ecommerce/urls.py
from django.contrib import admin
from django.urls import path,include
from .import views
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.home,name='home'),
    path('store/',include('store.urls')),
    path('carts/',include('carts.urls')),
    path('accounts/',include('accounts.urls')),
    path('orders/',include('orders.urls')),
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path
from .import views


urlpatterns = [
    path('store/',views.store,name="store"),
    path('category/<slug:category_slug>/',views.store,name="product_by_category"),
    path('category/<slug:category_slug>/<slug:product_slug>/',views.product_detail,name="product_detail"),
    path('search/',views.search,name="search"),
    path('submit_review/<int:product_id>/',views.submit_review,name="submit_review"),
]

carts/models.py
from django.db import models
from accounts.models import Account
from store.models import Product

# Create your models here.
class Cart(models.Model):
    cart_id=models.CharField(max_length=100)
    date_added=models.DateField(auto_now_add=True)

    def __str__(self):
        return self.cart_id

class CartItem(models.Model):
    product=models.ForeignKey(Product,on_delete=models.CASCADE,null=True,blank=True)
    cart=models.ForeignKey(Cart,on_delete=models.CASCADE,null=True,blank=True)
    variations=models.ManyToManyField('Variation',blank=True)
    quantity=models.IntegerField()
    is_active=models.BooleanField(default=True)
    user=models.ForeignKey(Account,on_delete=models.CASCADE,null=True,blank=True)

    def __unicode__(self):
        return self.product

    def sub_total(self):
        return self.product.price*self.quantity

variation_category_choice=(
    ('color','color'),
    ('size','size'),
)

class VariationManager(models.Manager):
    def colors(self):
        return super(VariationManager,self).filter(variation_category='color',is_active=True)

    def sizes(self):
        return super(VariationManager,self).filter(variation_category='size',is_active=True)

class Variation(models.Model):
    product=models.ForeignKey(Product,on_delete=models.CASCADE)
    variation_category=models.CharField(max_length=100,choices=variation_category_choice)
    variation_value=models.CharField(max_length=200)
    is_active=models.BooleanField(default=True)
    created_date=models.DateTimeField(auto_now=True)

    objects=VariationManager()
    def __unicode__(self):
        return self.product

    def __str__(self):
        return self.variation_value

store/models.py
from django.db import models
from category.models import Category
from django.urls import reverse

from accounts.models import Account


# Create your models here.
class Product(models.Model):
    product_name=models.CharField(max_length=100)
    images=models.ImageField(upload_to="photos/product")
    description=models.TextField(max_length=200)
    slug=models.SlugField(max_length=100)
    price=models.IntegerField()
    stock=models.IntegerField()
    is_available=models.BooleanField(default=True)
    upload_date=models.DateTimeField(auto_now_add=True)
    updated_date=models.DateTimeField(auto_now=True)
    category=models.ForeignKey(Category,on_delete=models.CASCADE)

    def get_url(self):
        return reverse('product_detail',args=[self.category.slug,self.slug])

    def __str__(self):
        return self.product_name

class ReviewRating(models.Model):
    product=models.ForeignKey(Product,on_delete=models.CASCADE)
    user=models.ForeignKey(Account,on_delete=models.CASCADE)
    subject=models.CharField(max_length=150,blank=True)
    review=models.TextField(max_length=600,blank=True)
    rating=models.FloatField()
    ip=models.CharField(max_length=200,blank=True)
    status=models.BooleanField(default=True)
    created_at=models.DateTimeField(auto_now_add=True)
    updated_at=models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.subject

store/forms.py
from django import forms

from .models import ReviewRating
class ReviewForm(forms.ModelForm):
    class Meta:
        model=ReviewRating
        fields=['subject','review','rating']

carts/views.py
from django.shortcuts import redirect, render
from store.models import Product
from .models import Cart,CartItem, Variation
from django.contrib.auth.decorators import login_required

# Create your views here.
def _cart_id(request):
    cart=request.session.session_key
    if not cart:
        cart=request.session.create()
    return cart
def add_cart(request,product_id):
    current_user=request.user
    product=Product.objects.get(id=product_id)
    if current_user.is_authenticated:


        product_variation=[]
        
        if request.method=="POST":
            for item in request.POST:
                key=item
                value=request.POST[key]
                try:
                    variation=Variation.objects.get(product=product,variation_category__iexact=key,variation_value__iexact=value)
                    product_variation.append(variation)
                    print(product_variation)
                except:
                    pass
    
        is_cart_item_exists=CartItem.objects.filter(product=product,user=current_user).exists()
        if is_cart_item_exists:
            cart_item=CartItem.objects.filter(product=product,user=current_user)
            ex_var_list=[]
            id=[]
            for item in cart_item:
                existing_variation=item.variations.all()
                ex_var_list.append(list(existing_variation))
                print(ex_var_list)
                id.append(item.id)
                print(id)
            if product_variation in ex_var_list:
                index=ex_var_list.index(product_variation)
                item_id=id[index]
                item=CartItem.objects.get(product=product,id=item_id)
                item.quantity+=1
                item.save()

            else:

                item=CartItem.objects.create(product=product,quantity=1,user=current_user)
                if len(product_variation)>0:
                    item.variations.clear()
                #for item in product_variation:
                    item.variations.add(*product_variation)
                    item.save()
        else:
            cart_item=CartItem.objects.create(
                product=product,
                quantity=1,
                user=current_user,
            )
            if len(product_variation)>0:
                cart_item.variations.clear()
                #for item in product_variation:
                cart_item.variations.add(*product_variation)
            cart_item.save()
        return redirect('carts')
    else:
        product_variation=[]

       
        if request.method=="POST":
            for item in request.POST:
                key=item
                value=request.POST[key]
                try:
                    variation=Variation.objects.get(product=product,variation_category__iexact=key,variation_value__iexact=value)
                    product_variation.append(variation)
                    print(product_variation)
                except:
                    pass
        try:
            cart=Cart.objects.get(cart_id=_cart_id(request))
        
        except Cart.DoesNotExist:
            cart=Cart.objects.create(
                cart_id=_cart_id(request)
            )
        cart.save()
        is_cart_item_exists=CartItem.objects.filter(product=product,cart=cart).exists()
        if is_cart_item_exists:
            cart_item=CartItem.objects.filter(product=product,cart=cart)
            ex_var_list=[]
            id=[]
            for item in cart_item:
                existing_variation=item.variations.all()
                ex_var_list.append(list(existing_variation))
                print(ex_var_list)
                id.append(item.id)
                print(id)
            if product_variation in ex_var_list:
                index=ex_var_list.index(product_variation)
                item_id=id[index]
                item=CartItem.objects.get(product=product,id=item_id)
                item.quantity+=1
                item.save()

            else:

                item=CartItem.objects.create(product=product,quantity=1,cart=cart)
                if len(product_variation)>0:
                    item.variations.clear()
                #for item in product_variation:
                    item.variations.add(*product_variation)
                    item.save()
        else:
            cart_item=CartItem.objects.create(
                product=product,
                quantity=1,
                cart=cart,
            )
            if len(product_variation)>0:
                cart_item.variations.clear()
                #for item in product_variation:
                cart_item.variations.add(*product_variation)
            cart_item.save()
        return redirect('carts')


def carts(request,total=0,quantity=0,cart_items=None):
    tax=0
    grand_total=0
    try:
        if request.user.is_authenticated:
             cart_items=CartItem.objects.filter(user=request.user,is_active=True)
        else:
            cart=Cart.objects.get(cart_id=_cart_id(request))
            cart_items=CartItem.objects.filter(cart=cart,is_active=True)
        for cart_item in cart_items:
            total=total+cart_item.product.price*cart_item.quantity
            quantity+=cart_item.quantity
            tax=(total*8)/100
            grand_total=total+tax
    except:
        pass
    context={
        'cart_items':cart_items,
        'total':total,
        'quantity':quantity,
        'tax':tax,
        'grand_total':grand_total,
    }


    return render(request,'store/carts.html',context)

def remove_cart(request,product_id,cart_item_id):
    product=Product.objects.get(id=product_id)
    if request.user.is_authenticated:
        cart_item=CartItem.objects.get(product=product,user=request.user,id=cart_item_id)
    else:
        cart=Cart.objects.get(cart_id=_cart_id(request))
        cart_item=CartItem.objects.get(product=product,cart=cart,id=cart_item_id)
    if cart_item.quantity>1:
        cart_item.quantity-=1
        cart_item.save()
    else:
        cart_item.delete()
    return redirect('carts')
    
def remove_cart_item(request,product_id,cart_item_id):
    product=Product.objects.get(id=product_id)
    if request.user.is_authenticated:
        cart_item=CartItem.objects.get(product=product,user=request.user,id=cart_item_id)
    else:
        cart=Cart.objects.get(cart_id=_cart_id(request))
        cart_item=CartItem.objects.get(product=product,cart=cart,id=cart_item_id)
    cart_item.delete()
    return redirect('carts')

@login_required(login_url='login')
def checkout(request):
    return render(request,'store/checkout.html')

store/views.py
from django.shortcuts import render,redirect
from .models import Product
from category.models import Category
from django.db.models import Q
from django.core.paginator import Paginator
from django.contrib import messages
from .models import ReviewRating
from .forms import ReviewForm


# Create your views here.
def store(request,category_slug=None):
    if category_slug!=None:
        categories=Category.objects.get(slug=category_slug)
        products=Product.objects.filter(category=categories)
        paginator=Paginator(products,2)
        page=request.GET.get('page')
        paged_products=paginator.get_page(page)

        product_count=products.count()
    else:
        products=Product.objects.filter(is_available=True)
        paginator=Paginator(products,2)
        page=request.GET.get('page')
        paged_products=paginator.get_page(page)
        product_count=products.count()
    

    context={
        'products':paged_products,
        'product_count':product_count,

    }
    return render(request,'store/store.html',context)

def product_detail(request,category_slug,product_slug):
    single_product=Product.objects.get(category__slug=category_slug,slug=product_slug)
    context={
        'single_product':single_product
    }
    return render(request,'store/product_detail.html',context)


def search(request):
    if 'keyword' in request.GET:
        keyword=request.GET.get('keyword')
        if keyword:
            products=Product.objects.order_by("-upload_date").filter(Q(description__icontains=keyword)|Q (product_name__icontains=keyword))
            product_count=products.count()
            context={
                'products':products,
                'product_count':product_count,
            }
        else:
            return redirect('store')
    return render(request,'store/store.html',context)

def submit_review(request,product_id):
    url=request.META.get('HTTP_REFERER')
    if request.method=="POST":
        #yaha par ham review update ka feature bana rahe
        try:
           reviews=ReviewRating.objects.get(user__id=request.user.id,product__id=product_id)
           form=ReviewForm(request.POST,instance=reviews)
           form.save()
           messages.success(request,"Thank you ! your review has been updated")
           return redirect(url)
        except ReviewRating.DoesNotExist:
            form=ReviewForm(request.POST)
            if form.is_valid():
                data=ReviewRating()
                data.subject=form.cleaned_data['subject']
                data.rating=form.cleaned_data['rating']
                data.review=form.cleaned_data['review']
                data.ip=request.META.get('REMOTE_ADDR')
                data.product_id=product_id
                data.user_id=request.user.id
                data.save()
                messages.success(request,"Thank You !your review has been submitted")
                return redirect(url)

templates/store/carts.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<section class="section-content padding-y bg">
    <div class="container">

        <!-- ============================ COMPONENT 1 ================================= -->
        {% if not cart_items %}
        <h1 class="text-center">Your Cart is Empty</h1>
        <div class="text-center">
            <a href="{% url 'store'%}" class="btn btn-primary ">Continue Shopping</a>
        </div>

        {% else %}
        <div class="row">
            <aside class="col-lg-9">
                <div class="card">
                    <table class="table table-borderless table-shopping-cart">
                        <thead class="text-muted">
                            <tr class="small text-uppercase">
                                <th scope="col">Product</th>
                                <th scope="col" width="120">Quantity</th>
                                <th scope="col" width="120">Price</th>
                                <th scope="col" class="text-right" width="200"> </th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for cart_item in cart_items %}
                            <tr>
                                <td>
                                    <figure class="itemside align-items-center">
                                        <div class="aside"><a href="{{cart_item.product.get_url}}"><img src="{{cart_item.product.images.url}}" class="img-sm"></a>
                                        </div>
                                        <figcaption class="info">
                                            <a href="{{cart_item.product.get_url}}" class="title text-dark">{{cart_item.product.product_name}}</a>
                                            {% if cart_item.variations.all %}
                                            {% for item in cart_item.variations.all %}
                                            <p class="text-muted small">{{item.variation_category}}: {{item.variation_value}}</p>
                                            {% endfor %}
                                            {% endif %}
                                        </figcaption>
                                    </figure>
                                </td>
                                <td>
                                    <!-- col.// -->
                                    <div class="col">
                                        <div class="input-group input-spinner">
                                            <div class="input-group-prepend">
                                                <a href="{% url 'remove_cart' cart_item.product.id cart_item.id %}"
                                                    class="btn btn-light" type="button" id="button-plus"> <i
                                                        class="fa fa-minus"></i> </a>
                                            </div>
                                            <input type="text" class="form-control" value="{{cart_item.quantity}}">
                                            <div class="input-group-append">
                                                <form action="{% url 'add_cart' cart_item.product.id %}" method="POST">
                                                  {% csrf_token %}
                                                  {% for item in cart_item.variations.all %}
                                                  <input type="hidden" name="{{item.variation_category}}" value="{{item.variation_value}}">
                                                  {% endfor %}

                                                   <button class="btn btn-light" type="submit" id="button-minus"><i class="fa fa-plus"></i></button>
                                                </form>
                                            </div>
                                        </div> <!-- input-group.// -->
                                    </div> <!-- col.// -->
                                </td>
                                <td>
                                    <div class="price-wrap">
                                        <var class="price">{{cart_item.sub_total}}</var>
                                        <small class="text-muted">{{cart_item.product.price}}</small>
                                    </div> <!-- price-wrap .// -->
                                </td>
                                <td class="text-right">
                                    <a href="{% url 'remove_cart_item' cart_item.product.id cart_item.id %}"
                                        class="btn btn-danger"> Remove</a>
                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div> <!-- card.// -->
                
                
            </aside> <!-- col.// -->
            <aside class="col-lg-3">

                <div class="card">
                    <div class="card-body">
                        <dl class="dlist-align">
                            <dt>Total price:</dt>
                            <dd class="text-right">{{total}}</dd>
                        </dl>
                        <dl class="dlist-align">
                            <dt>Tax:</dt>
                            <dd class="text-right">{{tax}}</dd>
                        </dl>
                        <dl class="dlist-align">
                            <dt>Grand Total:</dt>
                            <dd class="text-right text-dark b"><strong>{{grand_total}}</strong></dd>
                        </dl>
                        <hr>
                        <p class="text-center mb-3">
                            <img src="{% static './images/misc/payments.png' %}" height="26">
                        </p>
                        {% if request.user.is_authenticated %}
                        <a href="{% url 'checkout' %}" class="btn btn-primary btn-block"> Checkout </a>
                        {% else %}
                        <a href="{% url 'login' %}" class="btn btn-primary btn-block"> Checkout </a>
                        {% endif %}
                        <a href="{% url 'store' %}" class="btn btn-light btn-block">Continue Shopping</a>

                    </div> <!-- card-body.// -->
                </div> <!-- card.// -->
                

            </aside> <!-- col.// -->



        </div> <!-- row.// -->
        {% endif %}
        <!-- ============================ COMPONENT 1 END .// ================================= -->

    </div> <!-- container .//  -->
</section>
{% endblock %}

templates/store/product_detail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<!-- ============================ COMPONENT 1 ================================= -->
<div class="card">
    <div class="row no-gutters">
        <aside class="col-md-6">
            <article class="gallery-wrap">
                <div class="img-big-wrap">
                    <a href="#"><img src="{{single_product.images.url}}"></a>
                </div> <!-- img-big-wrap.// -->

            </article> <!-- gallery-wrap .end// -->
        </aside>
        <main class="col-md-6 border-left">
            <article class="content-body">
                <form method="POST" action="{% url 'add_cart' single_product.id %}">
                    {% csrf_token %}

                <h2 class="title">{{single_product.product_name}}</h2><hr>

                <div class="mb-3">
                    <h5>Price</h5>
                    <var class="price h4">{{single_product.price}}</var>
                </div>
               <h5>Description</h5>
                <p>{{single_product.description}}</p>


                <hr>
                <div class="row">
                    <div class="item-option-select">
                        <h6>Choose Color</h6>
                        <select name="color" class="form-control">
                            {% for i in single_product.variation_set.colors %}
                            <option value={{i.variation_value}}>{{i.variation_value}}</option>
                            {% endfor %}
                        </select>
                    </div>
                </div> <!-- row.// -->
                <div class="row">
                    <div class="item-option-select">
                        <select name="size" class="form-control">
                            {% for i in single_product.variation_set.sizes %}
                            <option value={{i.variation_value}}>{{i.variation_value}}</option>
                            {% endfor %}
                           
                        </select>
                    </div>
                </div> <!-- row.// -->
                <hr>
                {% if single_product.stock > 0 %}
                <button type="submit" class="btn  btn-primary"> <span class="text">Add to cart</span> <i class="fas fa-shopping-cart"></i></button>
                {% else %}
                <h1 class="btn btn-danger">Out of Stock</h1>
                {% endif %}
            </article> 
        </form> <!-- product-info-aside .// -->
        </main> <!-- col.// -->
    </div> <!-- row.// -->
</div> <!-- card.// -->
<!-- ============================ COMPONENT 1 END .// ================================= -->

<br>

<div class="row">
    <div class="col-md-9">

        <header class="section-heading">
            <h3>Customer Reviews </h3>

        </header>
        <form method="POST" action="{% url 'submit_review' single_product.id %}">
            {% csrf_token %}
            <h5>Write Your Reviews</h5>
            <div>
                <label>How do you rate this products</label>
                <br>
                <div class="rate">
                    <input type="radio" name="rating" id="rating10" value="5" required><label for="rating10" title="5"></label>
                    <input type="radio" name="rating" id="rating9" value="4.5" required><label for="rating9" title="4.5"></label>
                    <input type="radio" name="rating" id="rating8" value="4" required><label for="rating8" title="4"></label>
                    <input type="radio" name="rating" id="rating7" value="3.5" required><label for="rating7" title="3.5"></label>
                    <input type="radio" name="rating" id="rating6" value="3" required><label for="rating6" title="3"></label>
                    <input type="radio" name="rating" id="rating5" value="2.5" required><label for="rating5" title="2.5"></label>
                    <input type="radio" name="rating" id="rating4" value="2" required><label for="rating4" title="2"></label>
                    <input type="radio" name="rating" id="rating3" value="1.5" required><label for="rating3" title="1.5"></label>
                    <input type="radio" name="rating" id="rating2" value="1" required><label for="rating2" title="1"></label>
                    <input type="radio" name="rating" id="rating1" value="0.5" required><label for="rating1" title="0.5"></label>
            </div>
            Review Title:
            <input type="text" class="form-control" name="subject">
            <br>
          
            Review:
            <textarea name="review" class="form-control" rows="5"></textarea><br><br>

       <br> <article class="box mb-3">
            <div class="icontext w-100">
                <img src="{% static './images/avatars/avatar1.jpg' %}" class="img-xs icon rounded-circle">
                <div class="text">
                    <span class="date text-muted float-md-right">24.04.2020 </span>
                    <h6 class="mb-1">{{user.first_name}}</h6>

                </div>
            </div> <!-- icontext.// -->
            <div class="mt-3">
                <p>
                    Jawad is so smart !!!!
                </p>
            </div>
        </article><br>
        {% if user.is_authenticated %}
        <input type="submit" value="Submit Review" class="btn btn-primary">
{% else %}
<p>You must be logged in to post a review. <span><a href="{% url 'login' %}">Login now</a></span></p>
{% endif %}



    </div> <!-- col.// -->
</div> <!-- row.// -->


{% endblock %}